go.property("damage", 1)
go.property("projectiles_number", 3)
go.property("projectiles_factory", msg.url("/rangers_projectiles_factory#rangers_projectiles_factory"))

local ahash = require "ahash.ahash"
local sounds = require("scripts.sounds")

local function start_attack(self)
	msg.post(".", "enable")
	sounds:play("#jotun_attack_sfx", { speed = math.random(90, 110)/100 })
	local self_position = go.get_world_position()
	local target_pos = go.get_world_position("/player/player") + vmath.vector3(0, 2, 0)
	local delta = target_pos - self_position
	local desired_direction = vmath.normalize(delta)
	for i = 1, self.projectiles_number do
		local offset = vmath.vector3(math.random() * 3 - 1.5, math.random() * 4 - 2, math.random() * 3 - 1.5)
		msg.post(self.projectiles_factory, ahash.instantiate, { position = self_position + offset, direction = desired_direction })
	end
end

function on_message(self, message_id, message, sender)
	if message_id == ahash.start_attack then
		start_attack(self)
	end
end