return {
    data = {
        animations = {
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1.02,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1.02,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 1.02,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1.02,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "run",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = -7,
                    },
                    {
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_value = 28.000002,
                    },
                    {
                        easing = "outsine",
                        end_value = 25,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = -2,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_value = 25,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_value = -15,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_value = 15,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 28,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "position_y",
                        start_value = 28,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 28,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_value = 23,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -32,
                        key_type = "tween",
                        node_id = "arm_r",
                        property_id = "rotation_z",
                        start_value = -7,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 43.2,
                        key_type = "tween",
                        node_id = "arm_l",
                        property_id = "rotation_z",
                        start_value = 28.200000762939,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = -7,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 28,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        end_value = 20,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_time = 0.3,
                        start_value = 5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 26,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 28,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = -2,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -15,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = 15,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "arm_r",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 28,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 23,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 28.2,
                        key_type = "tween",
                        node_id = "arm_l",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = 43.2,
                    },
                    {
                        duration = 0.28,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_time = 0.52,
                        start_value = 20,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_time = 0.8,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.8,
                        start_value = -7,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_time = 0.8,
                        start_value = 5,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_time = 0.8,
                        start_value = 26,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 25,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_time = 0.8,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "bear_run",
                animation_keys = {
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -63.334,
                        key_type = "tween",
                        node_id = "bear_arm_l",
                        property_id = "rotation_z",
                        start_value = -53.333671569824,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -60.333,
                        key_type = "tween",
                        node_id = "bear_arm_r",
                        property_id = "rotation_z",
                        start_value = -75.333335876465,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1.05,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "position_y",
                        start_value = -7,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = 20,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 47,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "position_x",
                        start_value = 37,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 119,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "position_y",
                        start_value = 124,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 129,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "position_y",
                        start_value = 124,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -75,
                        key_type = "tween",
                        node_id = "bear_arm_r",
                        property_id = "rotation_z",
                        start_time = 0.25,
                        start_value = -60.333,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -53,
                        key_type = "tween",
                        node_id = "bear_arm_l",
                        property_id = "rotation_z",
                        start_time = 0.25,
                        start_value = -63.334,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "position_y",
                        start_time = 0.25,
                        start_value = 3,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "rotation_z",
                        start_time = 0.25,
                        start_value = 20,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "rotation_z",
                        start_time = 0.25,
                        start_value = -10,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "scale_y",
                        start_time = 0.25,
                        start_value = 1.05,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 37,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "position_x",
                        start_time = 0.25,
                        start_value = 47,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 124,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "position_y",
                        start_time = 0.25,
                        start_value = 129,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 124,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "position_y",
                        start_time = 0.25,
                        start_value = 119,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -85,
                        key_type = "tween",
                        node_id = "bear_arm_r",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -75,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -43,
                        key_type = "tween",
                        node_id = "bear_arm_l",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -53,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "rotation_z",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = -7,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = 10,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "rotation_z",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 134,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 124,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -75,
                        key_type = "tween",
                        node_id = "bear_arm_r",
                        property_id = "rotation_z",
                        start_time = 0.75,
                        start_value = -85,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        end_value = -53,
                        key_type = "tween",
                        node_id = "bear_arm_l",
                        property_id = "rotation_z",
                        start_time = 0.75,
                        start_value = -43,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "position_y",
                        start_time = 0.75,
                        start_value = 3,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "rotation_z",
                        start_time = 0.75,
                        start_value = -10,
                    },
                    {
                        duration = 0.25,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "rotation_z",
                        start_time = 0.75,
                        start_value = 10,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "bear_leg_l",
                        property_id = "scale_y",
                        start_time = 0.75,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        end_value = 124,
                        key_type = "tween",
                        node_id = "bear_leg_r",
                        property_id = "position_y",
                        start_time = 0.75,
                        start_value = 134,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "bear_idle",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1.01,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1.01,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 1.01,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "bear_body",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1.01,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "attack",
                animation_keys = {
                    {
                        data = "false",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "vfx",
                        property_id = "enabled",
                        start_data = "true",
                    },
                    {
                        data = "true",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "vfx",
                        property_id = "enabled",
                        start_data = "false",
                        start_time = 0.115,
                    },
                    {
                        data = "false",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "vfx",
                        property_id = "enabled",
                        start_data = "true",
                        start_time = 0.115,
                    },
                    {
                        data = "true",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "vfx",
                        property_id = "enabled",
                        start_data = "false",
                        start_time = 0.115,
                    },
                    {
                        data = "false",
                        easing = "linear",
                        key_type = "trigger",
                        node_id = "vfx",
                        property_id = "enabled",
                        start_data = "true",
                        start_time = 0.47,
                    },
                },
                duration = 0.5,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "player/player.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}