return {
    data = {
        animations = {
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1.02,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outquart",
                        end_value = 1.02,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 1.02,
                    },
                    {
                        duration = 0.4,
                        easing = "outquart",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 1.02,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "run",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = -7,
                    },
                    {
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                    },
                    {
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_value = 28.000002,
                    },
                    {
                        easing = "outsine",
                        end_value = 25,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = -2,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_value = 25,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_value = -15,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_value = 15,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 28,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "position_y",
                        start_value = 28,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 28,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_value = 23,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -32,
                        key_type = "tween",
                        node_id = "arm_r",
                        property_id = "rotation_z",
                        start_value = -7,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 43.2,
                        key_type = "tween",
                        node_id = "arm_l",
                        property_id = "rotation_z",
                        start_value = 28.200000762939,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = -7,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_time = 0.3,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 28,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        end_value = 20,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_time = 0.3,
                        start_value = 5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 26,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_time = 0.3,
                        start_value = 28,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = -2,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -15,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = 15,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -7,
                        key_type = "tween",
                        node_id = "arm_r",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = -32,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 28,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 23,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 28.2,
                        key_type = "tween",
                        node_id = "arm_l",
                        property_id = "rotation_z",
                        start_time = 0.5,
                        start_value = 43.2,
                    },
                    {
                        duration = 0.28,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_time = 0.52,
                        start_value = 20,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "rotation_z",
                        start_time = 0.8,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.8,
                        start_value = -7,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "pero",
                        property_id = "rotation_z",
                        start_time = 0.8,
                        start_value = 5,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "leg_r",
                        property_id = "position_y",
                        start_time = 0.8,
                        start_value = 26,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 25,
                        key_type = "tween",
                        node_id = "leg_l",
                        property_id = "rotation_z",
                        start_time = 0.8,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "player/player.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}