return {
    data = {
        animations = {
            {
                animation_id = "walking",
                animation_keys = {
                    {
                        duration = 0.15,
                        easing = "linear",
                        end_value = -20,
                        key_type = "tween",
                        node_id = "leg_left",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.15,
                        easing = "linear",
                        end_value = -15.341,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_value = -0.34131690859795,
                    },
                    {
                        duration = 0.15,
                        easing = "linear",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.15,
                        easing = "linear",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "leg_right",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_z",
                        start_time = 0.15,
                        start_value = 15,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = -5,
                        key_type = "tween",
                        node_id = "leg_right",
                        property_id = "rotation_z",
                        start_time = 0.15,
                        start_value = 15,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 10,
                        key_type = "tween",
                        node_id = "leg_left",
                        property_id = "rotation_z",
                        start_time = 0.15,
                        start_value = -20,
                    },
                    {
                        duration = 0.3,
                        easing = "insine",
                        end_value = 19.659,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_time = 0.15,
                        start_value = -15.341,
                    },
                    {
                        duration = 0.15,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_z",
                        start_time = 0.45,
                        start_value = -15,
                    },
                    {
                        duration = 0.15,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_time = 0.45,
                        start_value = 19.659,
                    },
                    {
                        duration = 0.15,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "leg_left",
                        property_id = "rotation_z",
                        start_time = 0.45,
                        start_value = 10,
                    },
                    {
                        duration = 0.15,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "leg_right",
                        property_id = "rotation_z",
                        start_time = 0.45,
                        start_value = -5,
                    },
                },
                duration = 0.6,
            },
            {
                animation_id = "death",
                animation_keys = {
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -10.341,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_value = -0.34131690859795,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 148,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "position_x",
                        start_value = 145,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 262,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "position_y",
                        start_value = 362,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = -172,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "position_x",
                        start_time = 0.2,
                        start_value = -137,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_z",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 260,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "position_y",
                        start_time = 0.2,
                        start_value = 360,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = -164,
                        key_type = "tween",
                        node_id = "leg_left",
                        property_id = "position_x",
                        start_time = 0.4,
                        start_value = -39,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 33,
                        key_type = "tween",
                        node_id = "leg_left",
                        property_id = "position_y",
                        start_time = 0.4,
                        start_value = 133,
                    },
                    {
                        duration = 0.6,
                        easing = "outsine",
                        end_value = 80,
                        key_type = "tween",
                        node_id = "leg_left",
                        property_id = "rotation_z",
                        start_time = 0.4,
                    },
                    {
                        duration = 0.54,
                        easing = "outsine",
                        end_value = 64,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.46,
                        start_value = 194,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = -80,
                        key_type = "tween",
                        node_id = "leg_right",
                        property_id = "rotation_z",
                        start_time = 0.5,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 23,
                        key_type = "tween",
                        node_id = "leg_right",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 133,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "leg_right",
                        property_id = "position_x",
                        start_time = 0.5,
                        start_value = 55,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 29.659,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_time = 0.52,
                        start_value = -10.341,
                    },
                    {
                        duration = 0.15,
                        easing = "outsine",
                        end_value = 42,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "position_y",
                        start_time = 0.52,
                        start_value = 262,
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = -352,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "position_x",
                        start_time = 0.52,
                        start_value = -172,
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "position_y",
                        start_time = 0.52,
                        start_value = 260,
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = 85,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_z",
                        start_time = 0.52,
                        start_value = 15,
                    },
                    {
                        duration = 0.48,
                        easing = "outsine",
                        end_value = -55,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_time = 0.52,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 199,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 194,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 365,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "position_y",
                        start_time = 0.15,
                        start_value = 360,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 367,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "position_y",
                        start_time = 0.15,
                        start_value = 362,
                    },
                    {
                        duration = 0.5,
                        easing = "outsine",
                        end_value = 194,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.5,
                        start_value = 199,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "position_y",
                        start_time = 0.65,
                        start_value = 365,
                    },
                    {
                        duration = 0.35,
                        easing = "outsine",
                        end_value = 362,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "position_y",
                        start_time = 0.65,
                        start_value = 367,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "attack",
                animation_keys = {
                    {
                        duration = 0.125,
                        easing = "outsine",
                        end_value = 10,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_y",
                    },
                    {
                        duration = 0.125,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_value = -0.34131690859795,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = -160,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 55,
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_y",
                    },
                    {
                        duration = 0.125,
                        easing = "outsine",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_y",
                        start_time = 0.125,
                        start_value = 10,
                    },
                    {
                        duration = 0.125,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_time = 0.125,
                        start_value = 15,
                    },
                    {
                        duration = 0.125,
                        easing = "outsine",
                        end_value = 50,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_y",
                        start_time = 0.25,
                        start_value = -10,
                    },
                    {
                        duration = 0.125,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_time = 0.25,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_y",
                        start_time = 0.34,
                        start_value = 55,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "arm_left",
                        property_id = "rotation_z",
                        start_time = 0.34,
                        start_value = -160,
                    },
                    {
                        duration = 0.125,
                        easing = "outsine",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_y",
                        start_time = 0.375,
                        start_value = 50,
                    },
                    {
                        duration = 0.125,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "arm_right",
                        property_id = "rotation_z",
                        start_time = 0.375,
                        start_value = 15,
                    },
                },
                duration = 0.5,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "enemies/jotun_ranger/jotun_ranger.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}