return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outquart",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "outquart",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_y",
                        start_time = 0.5,
                        start_value = 2,
                    },
                    {
                        duration = 0.4,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "root",
                        property_id = "scale_x",
                        start_time = 0.5,
                        start_value = 2,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
        },
        nodes = {
            {
                adjust_mode = "fit",
                blend_mode = "alpha",
                clipping_mode = "none",
                clipping_visible = true,
                color_a = 1,
                color_b = 1,
                color_g = 1,
                color_r = 1,
                enabled = true,
                inherit_alpha = true,
                node_id = "root",
                node_index = 1,
                node_type = "box",
                pivot = "pivot_center",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_mode = "auto",
                size_x = 200,
                size_y = 100,
                visible = true,
            },
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}