go.property("damage_per_tick", 1)
go.property("ticks_per_second", 5)

local trigger_response = hash("trigger_response")

local function reset_attack(self)
	self.attack_target_id = nil
	self.time_from_last_tick = 0
end

function init(self)
	self.tick_time = 1.0/self.ticks_per_second
	reset_attack(self)
	go.animate("#attack_view", "u_brightness_time", go.PLAYBACK_LOOP_PINGPONG, vmath.vector4(3.14, 0.0, 0.0, 0.0), go.EASING_LINEAR, 3.0)
	go.animate("#attack_view", "u_waving_time", go.PLAYBACK_LOOP_FORWARD, vmath.vector4(6.14, 0.0, 0.0, 0.0), go.EASING_LINEAR, 0.5)
end

function fixed_update(self, dt)
	if self.attack_target_id then
		self.time_from_last_tick = self.time_from_last_tick + dt
		if self.time_from_last_tick >= self.tick_time then
			msg.post(self.attack_target_id, hash("attack"), { damage = self.damage_per_tick, source_id = go.get_id() })
			self.time_from_last_tick = 0
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == trigger_response and message.other_group == hash("player") then
		if message.enter then
			self.attack_target_id = message.other_id
		else
			reset_attack(self)
		end
	end
end